# Generated by Django 6.1.1 on 2026-09-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('art_lover', 'Art Lover'), ('both', 'Artist & Art Lover')], default='art_lover', max_length=20),
        ),
    ]
